# organization name, it's used to get github repo url, also in page title
name: react-component

# badge style, can be "flat" or ""
# see https://badgen.net/ for details
badge_style: flat

# meta headers in html
title: react-component
description: React components foundation of ant.design
keywords: react-component, antd, ant design, react ui

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - wc-input-number:
     repo: kavience/wc-input-number


# list of maintainers, this won't be sorted
maintainers:
 - name:    Kavience
   github:  kavience
   npm:     kavience_owner
   twitter: kavience
   email:   kavience@gmail.com


# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
   - avatar
