name: Deploy GitHub Pages
on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build
        run: |
          make clean 
          make index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          BRANCH: gh-pages
          FOLDER: /
